[tool.poetry]
description = "Uploads results of web-tests to google sheets."
authors = ["Kameron Lutes <kalutes@google.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
google = "^3.0.0"
google-auth = "^2.39.0"
google-auth-oauthlib = "^1.2.2"
google-api-core = "^2.24.2"
google-api-python-client = "^2.167.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
