// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

export const importantMetricsManifest = {
  'browsing-multitab': [
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'browsing-multiwindow': [
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'browsing': [
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'cpu-stress': [
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'docs': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Event.ScrollJank.DelayedFramesPercentage.FixedWindow',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllInteractions',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_Loaded',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'gmail': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'meet-note': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'WebRTC.Video.DroppedFrames.Capturer',
    'WebRTC.Video.DroppedFrames.Encoder',
    'WebRTC.Video.DroppedFrames.Receiver',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'meet': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'WebRTC.Video.DroppedFrames.Capturer',
    'WebRTC.Video.DroppedFrames.Encoder',
    'WebRTC.Video.DroppedFrames.Receiver',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'open-close': [
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'page-click': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_Loaded',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'page-scroll': [
    'EventLatency.TotalLatency',
    'Event.ScrollJank.DelayedFramesPercentage.FixedWindow',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllInteractions',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_Loaded',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'sheets': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'simultaneous-load': [
    'Browser.Tabs.TotalSwitchDuration3',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'slides': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'tab-stress': [
    'Browser.Tabs.TotalSwitchDuration3',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'tiktok': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'video-playback-online-browser': [
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'cuj.video.dropped_frames_count',
    'cuj.video.dropped_frames_percent',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'videocall': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'youtube-watch-browse': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Event.ScrollJank.DelayedFramesPercentage.FixedWindow',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllInteractions',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'cuj.video_streaming.playback_dropped_frames',
    'cuj.video_streaming.playback_duration',
    'cuj.video_streaming.playback_resolution_height',
    'cuj.video_streaming.playback_resolution_width',
    'cuj.video_streaming.playback_total_frames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
  ],
  'youtube': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'cuj.video_streaming.playback_dropped_frames',
    'cuj.video_streaming.playback_duration',
    'cuj.video_streaming.playback_resolution_height',
    'cuj.video_streaming.playback_resolution_width',
    'cuj.video_streaming.playback_total_frames',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'click-input-latency': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'typing-input-latency': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'EventLatency.KeyPressed.TotalLatency',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'heavy-meet-note': [
    'EventLatency.TotalLatency',
    'PageLoad.InteractiveTiming.InputDelay3',
    'Graphics.Smoothness.Jank3.AllSequences',
    'Graphics.Smoothness.PercentDroppedFrames3.AllSequences',
    'Browser.Tabs.TotalSwitchDuration3',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_Loaded',
    'Browser.Tabs.TotalSwitchDuration3.NoSavedFrames_NotLoaded',
    'Browser.Tabs.TotalSwitchDuration3.WithSavedFrames',
    'WebRTC.Video.DroppedFrames.Capturer',
    'WebRTC.Video.DroppedFrames.Encoder',
    'WebRTC.Video.DroppedFrames.Receiver',
    'cpu.times.user_ns',
    'cpu.times.system_mode_ns',
    'PageLoad.PaintTiming.NavigationToFirstContentfulPaint',
  ],
  'jetstream_2.2': [
    'Total/Score',
    '3d-cube-SP/Score',
    '3d-raytrace-SP/Score',
    'Air/Score',
    'Babylon/Score',
    'Basic/Score',
    'Box2D/Score',
    'FlightPlanner/Score',
    'HashSet-wasm/Score',
    'ML/Score',
    'OfflineAssembler/Score',
    'UniPoker/Score',
    'WSL/Score',
    'acorn-wtb/Score',
    'ai-astar/Score',
  ],
  'motionmark_1.3': [
    'score',
    'Canvas Arcs/controller/score',
    'Canvas Arcs/score',
    'Canvas Lines/controller/score',
    'Canvas Lines/score',
    'Design/controller/score',
    'Design/score',
    'Images/controller/score',
    'Images/score',
    'Leaves/controller/score',
    'Leaves/score',
    'Multiply/controller/score',
    'Multiply/score',
    'Paths/controller/score',
    'Paths/score',
  ],
  'speedometer_3.1': [
    'Score',
    'Geomean',
    'Iteration-0-Total',
    'Iteration-1-Total',
    'Iteration-2-Total',
    'Iteration-3-Total',
    'Iteration-4-Total',
    'Iteration-5-Total',
    'Iteration-6-Total',
    'Iteration-7-Total',
    'Iteration-8-Total',
    'Iteration-9-Total',
  ],
  'loadline2-tablet': [
    'loadline2.score-amazon_product_interactive',
    'loadline2.score-amazon_product_visual',
    'loadline2.score-cnn_article_interactive',
    'loadline2.score-cnn_article_visual',
    'loadline2.score-google_doc_interactive',
    'loadline2.score-google_doc_visual',
    'loadline2.score-google_search_result_interactive',
    'loadline2.score-google_search_result_visual',
    'loadline2.score-youtube_video_interactive',
    'loadline2.score-youtube_video_visual',
  ],
};
