# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

query {
  id: "uma_histogram_summaries_query"
  table {
    table_name: "uma_histogram_summaries"
    module_name: "sql_packages.queries.uma_histogram_summaries"
    column_names: "hist_name"
    column_names: "enum_name"
    column_names: "agg_type"
    column_names: "value"
    column_names: "polarity"
  }
}

metric_spec: {
  id: "cuj.uma.lower_is_better"
  dimensions: "hist_name"
  dimensions: "agg_type"
  value: "value"
  polarity: LOWER_IS_BETTER
  query: {
    inner_query_id: "uma_histogram_summaries_query"
    filters {
      column_name: "polarity"
      op: EQUAL
      string_rhs: "LOWER_IS_BETTER"
    }
  }
}

metric_spec: {
  id: "cuj.uma.higher_is_better"
  dimensions: "hist_name"
  dimensions: "agg_type"
  value: "value"
  polarity: HIGHER_IS_BETTER
  query: {
    inner_query_id: "uma_histogram_summaries_query"
    filters {
      column_name: "polarity"
      op: EQUAL
      string_rhs: "HIGHER_IS_BETTER"
    }
  }
}

metric_spec: {
  id: "cuj.uma_histogram_summaries"
  dimensions: "hist_name"
  dimensions: "agg_type"
  value: "value"
  query: {
    inner_query_id: "uma_histogram_summaries_query"
    filters {
      column_name: "polarity"
      op: EQUAL
      string_rhs: "POLARITY_UNSPECIFIED"
    }
  }
}
