# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""
Gathers crossbench execution results and compiles them into a unified flat
metrics JSON file.

JSON Schema:
The output `metrics.json` uses a tabular (flat list) format for metrics
to maximize compatibility with data analysis pipelines (like Pandas,
BigQuery, etc.) and visualization tools.

{
  "metadata": {
    "run_id": "2026-07-16_161929"
  },
  "metrics": [
    {
      "test_name": "speedometer_3.1",
      # Corresponds to web-tests variant (e.g. from --variant flag)
      "variant": "default",
      "browser": "chrome_v150",
      "metric": "Score",             # The specific metric name
      "values": [36.7, 37.1],        # Array of float values
      "units": "score",
      "improvement_direction": "up"  # 'up', 'down', or ''
    },
    ...
  ]
}

Parsing Approach:
The module traverses the crossbench output directory (`results_dir`) to find
benchmark results. It parses two types of crossbench outputs:
1. JSON probes (Press benchmarks): Reads `{test.name}.json` which contains
   benchmark score structures.
2. Perfetto Protobufs (Trace summaries): Reads `v2_metrics.pb` generated by
   the trace processor.
   These are decoded using the generated protobuf bindings in `protoc/gen`.
"""

from __future__ import annotations

import json
from pathlib import Path

from protos.perfetto.trace_summary import file_pb2, v2_metric_pb2
from runner.test_discovery import enumerate_all_tests


def _parse_v2_metrics(pb_file: Path, test_name: str, variant: str,
                      browser: str) -> list[dict]:

  metric_polarity = v2_metric_pb2.TraceMetricV2Spec.MetricPolarity
  metrics = []
  summary = file_pb2.TraceSummary()
  summary.ParseFromString(pb_file.read_bytes())
  for bundle in summary.metric_bundles:
    for row in bundle.row:
      metric_dimensions = []
      for dimension in row.dimension:
        dimension_field = dimension.WhichOneof("value_oneof")
        if dimension_field == "string_value":
          dim_val = dimension.string_value
        elif dimension_field == "int64_value":
          dim_val = dimension.int64_value
        elif dimension_field == "double_value":
          dim_val = dimension.double_value
        elif dimension_field == "bool_value":
          dim_val = dimension.bool_value
        else:
          dim_val = "None"
        metric_dimensions.append(str(dim_val))

      for value_i, value in enumerate(row.values):
        if value_i >= len(bundle.specs):
          continue
        if value.WhichOneof("value_oneof") == "null_value":
          continue

        spec = bundle.specs[value_i]
        polarity = spec.polarity
        if polarity == metric_polarity.HIGHER_IS_BETTER:
          imp_dir = "up"
        elif polarity == metric_polarity.LOWER_IS_BETTER:
          imp_dir = "down"
        else:
          imp_dir = ""

        val = value.double_value
        metric_name = "-".join([spec.id, *metric_dimensions])

        which_unit = spec.WhichOneof("unit_oneof")
        if which_unit == "unit":
          unit = v2_metric_pb2.TraceMetricV2Spec.MetricUnit.Name(spec.unit)
        elif which_unit == "custom_unit":
          unit = spec.custom_unit
        else:
          unit = "unknown"

        metrics.append({
            "test_name": test_name,
            "variant": variant,
            "browser": browser,
            "metric": metric_name,
            "values": [val],
            "units": unit,
            "improvement_direction": imp_dir
        })
  return metrics


def _parse_probe_json(json_file: Path, test_name: str,
                      variant: str) -> list[dict]:
  metrics = []
  with json_file.open("r", encoding="utf-8") as f:
    data = json.load(f)

  for browser, browser_data in data.items():
    if not isinstance(browser_data, dict) or "data" not in browser_data:
      continue
    for metric_name, metric_info in browser_data["data"].items():
      if not isinstance(metric_info, dict) or "values" not in metric_info:
        continue

      metrics.append({
          "test_name":
              test_name,
          "variant":
              variant,
          "browser":
              browser,
          "metric":
              metric_name,
          "values":
              metric_info["values"],
          "units":
              "score",
          "improvement_direction":
              metric_info.get("improvement_direction", "up")
      })
  return metrics


def generate_metrics_json(results_dir: Path) -> None:
  all_tests = {t.full_name: t for t in enumerate_all_tests()}
  metrics = []

  for test_dir in results_dir.glob("*"):
    if not test_dir.is_dir() or test_dir.name not in all_tests:
      continue
    test_obj = all_tests[test_dir.name]

    for pass_dir in test_dir.glob("pass/*"):
      # 1. Parse JSON probe data (press benchmarks)
      json_file = pass_dir / f"{test_obj.name}.json"
      if json_file.exists():
        metrics.extend(
            _parse_probe_json(json_file, test_obj.name, test_obj.variant))

      # 2. Parse Perfetto v2_metrics.pb
      for pb_file in pass_dir.rglob("v2_metrics.pb"):
        # Extract browser from path (e.g. <timestamp>/<browser>/...)
        rel_parts = pb_file.relative_to(pass_dir).parts
        if len(rel_parts) > 1:
          browser = rel_parts[0]
          metrics.extend(
              _parse_v2_metrics(pb_file, test_obj.name, test_obj.variant,
                                browser))

  out_file = results_dir / "metrics.json"
  with out_file.open("w", encoding="utf-8") as f:
    json.dump({
        "metadata": {
            "run_id": results_dir.name
        },
        "metrics": metrics
    },
              f,
              indent=2)
